[package]
name = "iner-calc"
version = "0.1.0"
edition = "2021"

[dependencies]
factorial = "0.4.0"
itertools = "0.13.0"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"

[profile.release]
debug=true

[[bench]]
name="bench1"
harness=false